quadrantChart
    title Reach and engagement of campaigns
    x-axis Low Reach --> High Reach
    y-axis Low Engagement --> High Engagement
    quadrant-1 We should expand
    quadrant-2 Need to promote
    quadrant-3 Re-evaluate
    quadrant-4 May be improved
    "竞品A": [0.3, 0.6]
    "竞品B": [0.45, 0.23]
    "竞品C": [0.57, 0.69]
    "竞品D": [0.78, 0.34]
    "竞品E": [0.40, 0.34]
    "Our Target Product": [0.5, 0.6]